### ISSUE TITLE
How to contribute ros_ign gazebo plugins to repo?

### ISSUE THREAD

**Issue by addy1997** [gazebosim/ros_gz#148]
Hi there,

I have implemented a mimic_joint plugin for ros-ign gazebo. I am not able to find a specific directory/folder/branch to contribute. More about this [here](https://github.com/ignitionrobotics/ign-gazebo/pull/739)

**Comment by chapulina** [comment]
Thank you for the interest in contributing!

I noticed on that other pull request that you haven't managed to get the plugin to compile yet. That plugin will need to be completely rethought before it can be migrated from Gazebo classic to Ignition. I recommend you get familiar with [Ignition's architecture](https://ignitionrobotics.org/docs/all/architecture) and check out our [migration guides](https://community.gazebosim.org/t/migration-from-gazebo-classic-to-ignition-gazebo/805).

Once you've understood how Ignition works and how it is different from classic, I suggest you develop your plugin on a separate repository until you're sure it compiles, runs and does what it's supposed to do. Please don't open pull requests with code that you can't compile or run, because that takes time for developers to review, and we have quite a lot on our plates :wink: 

Once you have a plugin working, that plugin doesn't need to be merged into one of the official repositories. You can use it from your own repository. If you'd like to contribute it so it's available to the wider community, once you have it working, I think it will become easier to direct you to the correct repository to open a pull request against.

Good luck!
