### ISSUE TITLE
Status of Foxy branch

### ISSUE THREAD

**Issue by mjcarroll** [gazebosim/ros_gz#162]
In the process of moving over to github actions in (#159, #160, #161) and merging in some open pull requests (#158). I noticed that the `foxy` branch doesn't seem to actually be used.

The `foxy/distribution.yaml` confirms this: https://github.com/ros/rosdistro/blob/master/foxy/distribution.yaml#L3509-L3530

The release `tracks.yaml` also indicates this: https://github.com/ros2-gbp/ros_ign-release/blob/master/tracks.yaml#L15

Can the `foxy` branch be safely removed at this point?

**Comment by chapulina** [comment]
The `foxy` branch was created as part of https://github.com/ignitionrobotics/ros_ign/pull/150. Due to a limitation in Bloom (see https://github.com/ros-infrastructure/bloom/issues/517), we need to keep separate branches for `foxy` and `rolling` / `galactic` in order to release using different Ignition versions.

> The foxy/distribution.yaml confirms this

Good point, something to fix next time we make a `foxy` release

**Comment by chapulina** [comment]
> something to fix next time we make a foxy release

https://github.com/ros/rosdistro/pull/30274
