### ISSUE TITLE
Release for rolling?

### ISSUE THREAD

**Issue by ijnek** [gazebosim/ros_gz#300]
In a project I have, I was using ros_ign_bridge as a library (ie. ``#include "ros_ign_bridge/convert/sensor_msgs.hpp"``), rather than as a standalone node. 

Unfortunately, this broke on humble during the transition from ros_ign_bridge -> ros_gz_bridge. So I decided to change all ros_ign_bridge -> ros_gz_bridge in my project, but then now the rolling CI (which ran on the same branch) is failing because a release hasn't been made since the rename.

I could go about splitting up my humble and rolling branch and running CI separately, but the problem will disappear once ros_gz_bridge is available in rolling.

Could I request the maintainers for a release for rolling please?

**Comment by mjcarroll** [comment]
I have a large port from galactic to rolling to get in (#275) and then I think we will be good for a release.

**Comment by ijnek** [comment]
Just a very gentle ping on this @mjcarroll. Sorry if this is on your todo list already!

**Comment by ijnek** [comment]
Hi @mjcarroll, do you have any updates on making a release?

For a while, it's been like this:
* galactic / **rolling**: ros_ign
* humble: ros_gz (or ros_ign with a deprecation warning)

A release would help cutting-edge rolling users a lot. What are the roadblockers?

**Comment by mjcarroll** [comment]
I think we can manage a release.  @ahcorde any reason not to?

**Comment by ijnek** [comment]
Ping @ahcorde, thanks

**Comment by christophfroehlich** [comment]
Is this correct that it is still not released for rolling?

Furthermore, in contrast to the compatibility table in the README.md the ros2 branch is not compatible with fortress any more -> I have to use humble branch to compile it for rolling+fortress. Or have I missed something?

https://github.com/gazebosim/ros_gz/blob/7c62a1ce3cfb4eb3b54e1cfd092c9b63a9d5f255/ros_gz_sim/CMakeLists.txt#L38

**Comment by moriarty** [comment]
> Is this correct that it is still not released for rolling?
> 
> Furthermore, in contrast to the compatibility table in the README.md the ros2 branch is not compatible with fortress any more -> I have to use humble branch to compile it for rolling+fortress. Or have I missed something?
> 
> https://github.com/gazebosim/ros_gz/blob/7c62a1ce3cfb4eb3b54e1cfd092c9b63a9d5f255/ros_gz_sim/CMakeLists.txt#L38

I just ran into this too.
It looks like part of this PR: https://github.com/gazebosim/ros_gz/pull/302 broke `ros2` general compatibility as described in the README.md table:

![image](https://user-images.githubusercontent.com/55676/236549495-5866c9c9-a5ae-4069-8bd2-9a2292308f19.png)

PR 302 removed all the depend conditions from the package.xml, so if you take the `ros2` branch it only supports garden... `humble` still works (If you take the humble branch, but that is not what the table describes) but it is broken on `rolling` out of the box, you can no longer just use the `ros2` branch unless you go through the additional steps of installing gazebo garden but rolling + garden require installing from source?
@mjcarroll & @azeey was that intentional?

https://github.com/gazebosim/ros_gz/pull/302/files?file-filters%5B%5D=.xml&show-deleted-files=true&show-viewed-files=true

**Comment by mjcarroll** [comment]
For humble, you should now be using the `humble` branch.  I am making a release for rolling/iron and fortress.

**Comment by mjcarroll** [comment]
Fixing branch names in #387 and #388

**Comment by azeey** [comment]
I think it's okay to do Fortress/Rolling binary releases while Iron is still pending, but once it's released, we should switch to preparing for the Gazebo Harmonic/ROS J-turtle pairing. So in that sense, the `This branch is only compatible with Gazebo Garden forward.` message seems correct, albeit a little early.

**Comment by moriarty** [comment]
> I think it's okay to do Fortress/Rolling binary releases while Iron is still pending, but once it's released, we should switch to preparing for the Gazebo Harmonic/ROS J-turtle pairing. So in that sense, the `This branch is only compatible with Gazebo Garden forward.` message seems correct, albeit a little early.

:+1: If the `Fortress/Rolling` binary release also has a `rolling` branch that source builds can depend on similar to the `humble` branch then that sounds great
